# Generated by Django 5.2.8 on 2025-11-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
